"""empty message

Revision ID: 073b85a39490
Revises: f235deeee494
Create Date: 2020-11-18 23:11:00.024983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073b85a39490'
down_revision = 'f235deeee494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'languages', 'useradm', ['user_id'], ['id'])
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'useradm', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_column('languages', 'user_id')
    # ### end Alembic commands ###
