"""empty message

Revision ID: 1faa397151bf
Revises: 74edbab4f6a3
Create Date: 2020-11-26 16:28:38.774925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faa397151bf'
down_revision = '74edbab4f6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('languages_ibfk_1', 'languages', type_='foreignkey')
    op.create_foreign_key(None, 'languages', 'users', ['user_id'], ['flag'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.create_foreign_key('languages_ibfk_1', 'languages', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
