"""empty message

Revision ID: 41029dcac86d
Revises: 65c9d7d3ece2
Create Date: 2020-11-23 03:17:08.420898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41029dcac86d'
down_revision = '65c9d7d3ece2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useradm', sa.Column('contato', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useradm', 'contato')
    # ### end Alembic commands ###
