"""empty message

Revision ID: 55c032c9bf08
Revises: 36f00a00c85f
Create Date: 2020-12-26 15:40:21.894650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c032c9bf08'
down_revision = '36f00a00c85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'response', ['name'], unique=True)
    # ### end Alembic commands ###
