"""empty message

Revision ID: 5a8a8bc035a4
Revises: 55c032c9bf08
Create Date: 2020-12-26 16:30:48.449463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8a8bc035a4'
down_revision = '55c032c9bf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('response_ibfk_1', 'response', type_='foreignkey')
    op.create_foreign_key(None, 'response', 'comments', ['comments_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.create_foreign_key('response_ibfk_1', 'response', 'comments', ['comments_id'], ['id'])
    # ### end Alembic commands ###
