"""empty message

Revision ID: 670bd7d5a21e
Revises: 223dd6cc2920
Create Date: 2020-11-26 13:24:17.486599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670bd7d5a21e'
down_revision = '223dd6cc2920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
