"""empty message

Revision ID: 7936db1dea7a
Revises: 0ee6ce47683e
Create Date: 2021-02-04 15:35:12.168171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7936db1dea7a'
down_revision = '0ee6ce47683e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img1', sa.String(length=60), nullable=True))
    op.add_column('posts', sa.Column('img2', sa.String(length=60), nullable=True))
    op.add_column('posts', sa.Column('img3', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img3')
    op.drop_column('posts', 'img2')
    op.drop_column('posts', 'img1')
    # ### end Alembic commands ###
