"""empty message

Revision ID: 9b1aaa6360df
Revises: 670bd7d5a21e
Create Date: 2020-11-26 15:50:34.468355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1aaa6360df'
down_revision = '670bd7d5a21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('languages_ibfk_1', 'languages', type_='foreignkey')
    op.create_foreign_key(None, 'languages', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_2', 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.create_foreign_key('languages_ibfk_1', 'languages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
