"""empty message

Revision ID: a7c3a785d33e
Revises: f203f256c4b3
Create Date: 2021-02-05 14:53:41.886779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c3a785d33e'
down_revision = 'f203f256c4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('forum_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'forum', ['forum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'forum_id')
    op.drop_table('forum')
    # ### end Alembic commands ###
