"""empty message

Revision ID: aca72c6b95eb
Revises: 0f41ffd3bff3
Create Date: 2020-11-26 16:03:41.109259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca72c6b95eb'
down_revision = '0f41ffd3bff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('userflag', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'languages', 'users', ['userflag'], ['flag'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_column('languages', 'userflag')
    # ### end Alembic commands ###
