"""empty message

Revision ID: b3b391407be7
Revises: aca72c6b95eb
Create Date: 2020-11-26 16:04:49.482605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b391407be7'
down_revision = 'aca72c6b95eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'languages', 'users', ['userflag'], ['flag'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    # ### end Alembic commands ###
