"""empty message

Revision ID: cba520b94a9b
Revises: 1faa397151bf
Create Date: 2020-11-26 16:29:13.632941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba520b94a9b'
down_revision = '1faa397151bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'languages', 'users', ['user_id'], ['flag'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    # ### end Alembic commands ###
