"""empty message

Revision ID: efb4a4e4fbac
Revises: 7936db1dea7a
Create Date: 2021-02-04 17:35:58.291977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb4a4e4fbac'
down_revision = '7936db1dea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'comments', ['name'], unique=True)
    # ### end Alembic commands ###
