"""empty message

Revision ID: f203f256c4b3
Revises: efb4a4e4fbac
Create Date: 2021-02-04 17:47:21.686222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f203f256c4b3'
down_revision = 'efb4a4e4fbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'text2')
    # ### end Alembic commands ###
